/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 118
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_BANG = 1,
  anon_sym_version = 2,
  aux_sym_running_version_token1 = 3,
  anon_sym_no = 4,
  anon_sym_service = 5,
  anon_sym_pad = 6,
  anon_sym_hostname = 7,
  sym_value = 8,
  anon_sym_alias = 9,
  anon_sym_exec = 10,
  anon_sym_foo = 11,
  sym_alias = 12,
  sym_command = 13,
  anon_sym_line = 14,
  anon_sym_console = 15,
  anon_sym_tty0 = 16,
  anon_sym_activation_DASHcharacter = 17,
  sym_ascii_value = 18,
  anon_sym_archive = 19,
  anon_sym_end = 20,
  anon_sym_path = 21,
  sym_file_path = 22,
  anon_sym_async_DASHbootp = 23,
  anon_sym_bootfile = 24,
  sym_async_bootp_hostname = 25,
  sym_async_bootp_data = 26,
  sym_configuration_file = 27,
  sym__running_version = 28,
  sym_running_version = 29,
  sym_service_section = 30,
  sym__configured_version = 31,
  sym_configured_version = 32,
  sym_service_statements = 33,
  sym_hostname_section = 34,
  sym__alias_section = 35,
  sym_alias_statement = 36,
  sym_mode = 37,
  sym_line_section = 38,
  sym_line_type = 39,
  sym_activation_character = 40,
  sym_archive_section = 41,
  sym__archive_path = 42,
  sym_async_bootp_section = 43,
  sym_async_bootp_tag = 44,
  aux_sym__alias_section_repeat1 = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_BANG] = "!",
  [anon_sym_version] = "version",
  [aux_sym_running_version_token1] = "running_version_token1",
  [anon_sym_no] = "no",
  [anon_sym_service] = "service",
  [anon_sym_pad] = "pad",
  [anon_sym_hostname] = "hostname",
  [sym_value] = "value",
  [anon_sym_alias] = "alias",
  [anon_sym_exec] = "exec",
  [anon_sym_foo] = "foo",
  [sym_alias] = "alias",
  [sym_command] = "command",
  [anon_sym_line] = "line",
  [anon_sym_console] = "console",
  [anon_sym_tty0] = "tty0",
  [anon_sym_activation_DASHcharacter] = "activation-character",
  [sym_ascii_value] = "ascii_value",
  [anon_sym_archive] = "archive",
  [anon_sym_end] = "end",
  [anon_sym_path] = "path",
  [sym_file_path] = "file_path",
  [anon_sym_async_DASHbootp] = "async-bootp",
  [anon_sym_bootfile] = "bootfile",
  [sym_async_bootp_hostname] = "async_bootp_hostname",
  [sym_async_bootp_data] = "async_bootp_data",
  [sym_configuration_file] = "configuration_file",
  [sym__running_version] = "_running_version",
  [sym_running_version] = "running_version",
  [sym_service_section] = "service_section",
  [sym__configured_version] = "_configured_version",
  [sym_configured_version] = "configured_version",
  [sym_service_statements] = "service_statements",
  [sym_hostname_section] = "hostname_section",
  [sym__alias_section] = "_alias_section",
  [sym_alias_statement] = "alias_statement",
  [sym_mode] = "mode",
  [sym_line_section] = "line_section",
  [sym_line_type] = "line_type",
  [sym_activation_character] = "activation_character",
  [sym_archive_section] = "archive_section",
  [sym__archive_path] = "_archive_path",
  [sym_async_bootp_section] = "async_bootp_section",
  [sym_async_bootp_tag] = "async_bootp_tag",
  [aux_sym__alias_section_repeat1] = "_alias_section_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_version] = anon_sym_version,
  [aux_sym_running_version_token1] = aux_sym_running_version_token1,
  [anon_sym_no] = anon_sym_no,
  [anon_sym_service] = anon_sym_service,
  [anon_sym_pad] = anon_sym_pad,
  [anon_sym_hostname] = anon_sym_hostname,
  [sym_value] = sym_value,
  [anon_sym_alias] = anon_sym_alias,
  [anon_sym_exec] = anon_sym_exec,
  [anon_sym_foo] = anon_sym_foo,
  [sym_alias] = sym_alias,
  [sym_command] = sym_command,
  [anon_sym_line] = anon_sym_line,
  [anon_sym_console] = anon_sym_console,
  [anon_sym_tty0] = anon_sym_tty0,
  [anon_sym_activation_DASHcharacter] = anon_sym_activation_DASHcharacter,
  [sym_ascii_value] = sym_ascii_value,
  [anon_sym_archive] = anon_sym_archive,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_path] = anon_sym_path,
  [sym_file_path] = sym_file_path,
  [anon_sym_async_DASHbootp] = anon_sym_async_DASHbootp,
  [anon_sym_bootfile] = anon_sym_bootfile,
  [sym_async_bootp_hostname] = sym_async_bootp_hostname,
  [sym_async_bootp_data] = sym_async_bootp_data,
  [sym_configuration_file] = sym_configuration_file,
  [sym__running_version] = sym__running_version,
  [sym_running_version] = sym_running_version,
  [sym_service_section] = sym_service_section,
  [sym__configured_version] = sym__configured_version,
  [sym_configured_version] = sym_configured_version,
  [sym_service_statements] = sym_service_statements,
  [sym_hostname_section] = sym_hostname_section,
  [sym__alias_section] = sym__alias_section,
  [sym_alias_statement] = sym_alias_statement,
  [sym_mode] = sym_mode,
  [sym_line_section] = sym_line_section,
  [sym_line_type] = sym_line_type,
  [sym_activation_character] = sym_activation_character,
  [sym_archive_section] = sym_archive_section,
  [sym__archive_path] = sym__archive_path,
  [sym_async_bootp_section] = sym_async_bootp_section,
  [sym_async_bootp_tag] = sym_async_bootp_tag,
  [aux_sym__alias_section_repeat1] = aux_sym__alias_section_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_version] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_running_version_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_no] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_service] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pad] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_hostname] = {
    .visible = true,
    .named = false,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_alias] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_exec] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_foo] = {
    .visible = true,
    .named = false,
  },
  [sym_alias] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_line] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_console] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tty0] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_activation_DASHcharacter] = {
    .visible = true,
    .named = false,
  },
  [sym_ascii_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_archive] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_path] = {
    .visible = true,
    .named = false,
  },
  [sym_file_path] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_async_DASHbootp] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bootfile] = {
    .visible = true,
    .named = false,
  },
  [sym_async_bootp_hostname] = {
    .visible = true,
    .named = true,
  },
  [sym_async_bootp_data] = {
    .visible = true,
    .named = true,
  },
  [sym_configuration_file] = {
    .visible = true,
    .named = true,
  },
  [sym__running_version] = {
    .visible = false,
    .named = true,
  },
  [sym_running_version] = {
    .visible = true,
    .named = true,
  },
  [sym_service_section] = {
    .visible = true,
    .named = true,
  },
  [sym__configured_version] = {
    .visible = false,
    .named = true,
  },
  [sym_configured_version] = {
    .visible = true,
    .named = true,
  },
  [sym_service_statements] = {
    .visible = true,
    .named = true,
  },
  [sym_hostname_section] = {
    .visible = true,
    .named = true,
  },
  [sym__alias_section] = {
    .visible = false,
    .named = true,
  },
  [sym_alias_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_mode] = {
    .visible = true,
    .named = true,
  },
  [sym_line_section] = {
    .visible = true,
    .named = true,
  },
  [sym_line_type] = {
    .visible = true,
    .named = true,
  },
  [sym_activation_character] = {
    .visible = true,
    .named = true,
  },
  [sym_archive_section] = {
    .visible = true,
    .named = true,
  },
  [sym__archive_path] = {
    .visible = false,
    .named = true,
  },
  [sym_async_bootp_section] = {
    .visible = true,
    .named = true,
  },
  [sym_async_bootp_tag] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__alias_section_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_configured_version = 1,
  field_running_version = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_configured_version] = "configured_version",
  [field_running_version] = "running_version",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_running_version, 1, .inherited = true},
  [1] =
    {field_running_version, 2},
  [2] =
    {field_configured_version, 1},
  [3] =
    {field_configured_version, 0, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(93);
      ADVANCE_MAP(
        '!', 94,
        '"', 91,
        ':', 92,
        'a', 16,
        'b', 60,
        'c', 54,
        'e', 47,
        'f', 63,
        'h', 55,
        'l', 37,
        'n', 56,
        'p', 6,
        's', 22,
        't', 77,
        'v', 30,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(112);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(106);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(120);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(17);
      END_STATE();
    case 5:
      if (lookahead == '0') ADVANCE(110);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(46);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(70);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(71);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(19);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(80);
      END_STATE();
    case 12:
      if (lookahead == 'b') ADVANCE(65);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(34);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(103);
      END_STATE();
    case 15:
      if (lookahead == 'c') ADVANCE(3);
      END_STATE();
    case 16:
      if (lookahead == 'c') ADVANCE(78);
      if (lookahead == 'l') ADVANCE(36);
      if (lookahead == 'r') ADVANCE(13);
      if (lookahead == 's') ADVANCE(86);
      END_STATE();
    case 17:
      if (lookahead == 'c') ADVANCE(35);
      END_STATE();
    case 18:
      if (lookahead == 'c') ADVANCE(26);
      END_STATE();
    case 19:
      if (lookahead == 'c') ADVANCE(81);
      END_STATE();
    case 20:
      if (lookahead == 'd') ADVANCE(114);
      END_STATE();
    case 21:
      if (lookahead == 'd') ADVANCE(99);
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(67);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(108);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(113);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(109);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(98);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(118);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(100);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(69);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(68);
      END_STATE();
    case 32:
      if (lookahead == 'f') ADVANCE(43);
      END_STATE();
    case 33:
      if (lookahead == 'h') ADVANCE(115);
      END_STATE();
    case 34:
      if (lookahead == 'h') ADVANCE(39);
      END_STATE();
    case 35:
      if (lookahead == 'h') ADVANCE(8);
      END_STATE();
    case 36:
      if (lookahead == 'i') ADVANCE(9);
      END_STATE();
    case 37:
      if (lookahead == 'i') ADVANCE(51);
      END_STATE();
    case 38:
      if (lookahead == 'i') ADVANCE(82);
      END_STATE();
    case 39:
      if (lookahead == 'i') ADVANCE(83);
      END_STATE();
    case 40:
      if (lookahead == 'i') ADVANCE(18);
      END_STATE();
    case 41:
      if (lookahead == 'i') ADVANCE(62);
      END_STATE();
    case 42:
      if (lookahead == 'i') ADVANCE(64);
      END_STATE();
    case 43:
      if (lookahead == 'i') ADVANCE(45);
      END_STATE();
    case 44:
      if (lookahead == 'l') ADVANCE(25);
      END_STATE();
    case 45:
      if (lookahead == 'l') ADVANCE(27);
      END_STATE();
    case 46:
      if (lookahead == 'm') ADVANCE(28);
      END_STATE();
    case 47:
      if (lookahead == 'n') ADVANCE(20);
      if (lookahead == 'x') ADVANCE(29);
      END_STATE();
    case 48:
      if (lookahead == 'n') ADVANCE(95);
      END_STATE();
    case 49:
      if (lookahead == 'n') ADVANCE(74);
      END_STATE();
    case 50:
      if (lookahead == 'n') ADVANCE(4);
      END_STATE();
    case 51:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 52:
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 53:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 54:
      if (lookahead == 'o') ADVANCE(49);
      END_STATE();
    case 55:
      if (lookahead == 'o') ADVANCE(72);
      END_STATE();
    case 56:
      if (lookahead == 'o') ADVANCE(97);
      END_STATE();
    case 57:
      if (lookahead == 'o') ADVANCE(104);
      END_STATE();
    case 58:
      if (lookahead == 'o') ADVANCE(44);
      END_STATE();
    case 59:
      if (lookahead == 'o') ADVANCE(75);
      END_STATE();
    case 60:
      if (lookahead == 'o') ADVANCE(59);
      END_STATE();
    case 61:
      if (lookahead == 'o') ADVANCE(76);
      END_STATE();
    case 62:
      if (lookahead == 'o') ADVANCE(48);
      END_STATE();
    case 63:
      if (lookahead == 'o') ADVANCE(57);
      END_STATE();
    case 64:
      if (lookahead == 'o') ADVANCE(50);
      END_STATE();
    case 65:
      if (lookahead == 'o') ADVANCE(61);
      END_STATE();
    case 66:
      if (lookahead == 'p') ADVANCE(117);
      END_STATE();
    case 67:
      if (lookahead == 'r') ADVANCE(84);
      END_STATE();
    case 68:
      if (lookahead == 'r') ADVANCE(111);
      END_STATE();
    case 69:
      if (lookahead == 'r') ADVANCE(73);
      END_STATE();
    case 70:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 71:
      if (lookahead == 's') ADVANCE(102);
      END_STATE();
    case 72:
      if (lookahead == 's') ADVANCE(79);
      END_STATE();
    case 73:
      if (lookahead == 's') ADVANCE(41);
      END_STATE();
    case 74:
      if (lookahead == 's') ADVANCE(58);
      END_STATE();
    case 75:
      if (lookahead == 't') ADVANCE(32);
      END_STATE();
    case 76:
      if (lookahead == 't') ADVANCE(66);
      END_STATE();
    case 77:
      if (lookahead == 't') ADVANCE(85);
      END_STATE();
    case 78:
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 79:
      if (lookahead == 't') ADVANCE(53);
      END_STATE();
    case 80:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 81:
      if (lookahead == 't') ADVANCE(31);
      END_STATE();
    case 82:
      if (lookahead == 'v') ADVANCE(11);
      END_STATE();
    case 83:
      if (lookahead == 'v') ADVANCE(24);
      END_STATE();
    case 84:
      if (lookahead == 'v') ADVANCE(40);
      END_STATE();
    case 85:
      if (lookahead == 'y') ADVANCE(5);
      END_STATE();
    case 86:
      if (lookahead == 'y') ADVANCE(52);
      END_STATE();
    case 87:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(87);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 88:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(88);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 89:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(89);
      if (('/' <= lookahead && lookahead <= ':') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 90:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(90);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      END_STATE();
    case 91:
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(2);
      END_STATE();
    case 92:
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_version);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_running_version_token1);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_no);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_service);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_pad);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_hostname);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_value);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_alias);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_exec);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_foo);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_alias);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_command);
      if (lookahead == ' ') ADVANCE(106);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_command);
      if (lookahead == ' ' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_line);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_console);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_tty0);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_activation_DASHcharacter);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_ascii_value);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(112);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_archive);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_path);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_file_path);
      if (('/' <= lookahead && lookahead <= ':') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_async_DASHbootp);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_bootfile);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_async_bootp_hostname);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_async_bootp_data);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 87},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 87},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 88},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 88},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 89},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 90},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_version] = ACTIONS(1),
    [anon_sym_no] = ACTIONS(1),
    [anon_sym_service] = ACTIONS(1),
    [anon_sym_pad] = ACTIONS(1),
    [anon_sym_hostname] = ACTIONS(1),
    [anon_sym_alias] = ACTIONS(1),
    [anon_sym_exec] = ACTIONS(1),
    [anon_sym_foo] = ACTIONS(1),
    [anon_sym_line] = ACTIONS(1),
    [anon_sym_console] = ACTIONS(1),
    [anon_sym_tty0] = ACTIONS(1),
    [anon_sym_activation_DASHcharacter] = ACTIONS(1),
    [sym_ascii_value] = ACTIONS(1),
    [anon_sym_archive] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_path] = ACTIONS(1),
    [anon_sym_async_DASHbootp] = ACTIONS(1),
    [anon_sym_bootfile] = ACTIONS(1),
    [sym_async_bootp_hostname] = ACTIONS(1),
    [sym_async_bootp_data] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_configuration_file] = STATE(98),
    [anon_sym_BANG] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 18,
    ACTIONS(5), 1,
      ts_builtin_sym_end,
    ACTIONS(7), 1,
      anon_sym_BANG,
    ACTIONS(9), 1,
      anon_sym_version,
    ACTIONS(11), 1,
      anon_sym_no,
    ACTIONS(13), 1,
      anon_sym_hostname,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(17), 1,
      anon_sym_line,
    ACTIONS(19), 1,
      anon_sym_archive,
    ACTIONS(21), 1,
      anon_sym_async_DASHbootp,
    STATE(3), 1,
      sym_service_section,
    STATE(4), 1,
      sym_archive_section,
    STATE(8), 1,
      sym_async_bootp_section,
    STATE(17), 1,
      sym_line_section,
    STATE(37), 1,
      sym_hostname_section,
    STATE(46), 1,
      sym__configured_version,
    STATE(86), 1,
      sym_service_statements,
    STATE(102), 1,
      sym__alias_section,
    STATE(42), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [56] = 13,
    ACTIONS(13), 1,
      anon_sym_hostname,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(17), 1,
      anon_sym_line,
    ACTIONS(19), 1,
      anon_sym_archive,
    ACTIONS(21), 1,
      anon_sym_async_DASHbootp,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      anon_sym_BANG,
    STATE(5), 1,
      sym_archive_section,
    STATE(7), 1,
      sym_async_bootp_section,
    STATE(14), 1,
      sym_line_section,
    STATE(23), 1,
      sym_hostname_section,
    STATE(100), 1,
      sym__alias_section,
    STATE(42), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [97] = 11,
    ACTIONS(13), 1,
      anon_sym_hostname,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(17), 1,
      anon_sym_line,
    ACTIONS(21), 1,
      anon_sym_async_DASHbootp,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      anon_sym_BANG,
    STATE(6), 1,
      sym_async_bootp_section,
    STATE(12), 1,
      sym_line_section,
    STATE(28), 1,
      sym_hostname_section,
    STATE(68), 1,
      sym__alias_section,
    STATE(42), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [132] = 11,
    ACTIONS(13), 1,
      anon_sym_hostname,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(17), 1,
      anon_sym_line,
    ACTIONS(21), 1,
      anon_sym_async_DASHbootp,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(31), 1,
      anon_sym_BANG,
    STATE(9), 1,
      sym_async_bootp_section,
    STATE(13), 1,
      sym_line_section,
    STATE(25), 1,
      sym_hostname_section,
    STATE(71), 1,
      sym__alias_section,
    STATE(42), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [167] = 9,
    ACTIONS(13), 1,
      anon_sym_hostname,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(17), 1,
      anon_sym_line,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(33), 1,
      anon_sym_BANG,
    STATE(16), 1,
      sym_line_section,
    STATE(30), 1,
      sym_hostname_section,
    STATE(83), 1,
      sym__alias_section,
    STATE(42), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [196] = 9,
    ACTIONS(13), 1,
      anon_sym_hostname,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(17), 1,
      anon_sym_line,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      anon_sym_BANG,
    STATE(15), 1,
      sym_line_section,
    STATE(22), 1,
      sym_hostname_section,
    STATE(75), 1,
      sym__alias_section,
    STATE(42), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [225] = 9,
    ACTIONS(13), 1,
      anon_sym_hostname,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(17), 1,
      anon_sym_line,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(37), 1,
      anon_sym_BANG,
    STATE(10), 1,
      sym_line_section,
    STATE(24), 1,
      sym_hostname_section,
    STATE(88), 1,
      sym__alias_section,
    STATE(42), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [254] = 9,
    ACTIONS(13), 1,
      anon_sym_hostname,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(17), 1,
      anon_sym_line,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(41), 1,
      anon_sym_BANG,
    STATE(11), 1,
      sym_line_section,
    STATE(32), 1,
      sym_hostname_section,
    STATE(99), 1,
      sym__alias_section,
    STATE(42), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [283] = 7,
    ACTIONS(13), 1,
      anon_sym_hostname,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(43), 1,
      anon_sym_BANG,
    STATE(31), 1,
      sym_hostname_section,
    STATE(117), 1,
      sym__alias_section,
    STATE(42), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [306] = 7,
    ACTIONS(13), 1,
      anon_sym_hostname,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    ACTIONS(47), 1,
      anon_sym_BANG,
    STATE(38), 1,
      sym_hostname_section,
    STATE(113), 1,
      sym__alias_section,
    STATE(42), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [329] = 7,
    ACTIONS(13), 1,
      anon_sym_hostname,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(49), 1,
      anon_sym_BANG,
    STATE(29), 1,
      sym_hostname_section,
    STATE(81), 1,
      sym__alias_section,
    STATE(42), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [352] = 7,
    ACTIONS(13), 1,
      anon_sym_hostname,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(51), 1,
      anon_sym_BANG,
    STATE(35), 1,
      sym_hostname_section,
    STATE(97), 1,
      sym__alias_section,
    STATE(42), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [375] = 7,
    ACTIONS(13), 1,
      anon_sym_hostname,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 1,
      anon_sym_BANG,
    STATE(27), 1,
      sym_hostname_section,
    STATE(69), 1,
      sym__alias_section,
    STATE(42), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [398] = 7,
    ACTIONS(13), 1,
      anon_sym_hostname,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(55), 1,
      anon_sym_BANG,
    STATE(36), 1,
      sym_hostname_section,
    STATE(103), 1,
      sym__alias_section,
    STATE(42), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [421] = 7,
    ACTIONS(13), 1,
      anon_sym_hostname,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(57), 1,
      anon_sym_BANG,
    STATE(34), 1,
      sym_hostname_section,
    STATE(107), 1,
      sym__alias_section,
    STATE(42), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [444] = 7,
    ACTIONS(13), 1,
      anon_sym_hostname,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(59), 1,
      anon_sym_BANG,
    STATE(26), 1,
      sym_hostname_section,
    STATE(74), 1,
      sym__alias_section,
    STATE(42), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [467] = 2,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
    ACTIONS(64), 6,
      anon_sym_BANG,
      anon_sym_hostname,
      anon_sym_alias,
      anon_sym_line,
      anon_sym_archive,
      anon_sym_async_DASHbootp,
  [479] = 1,
    ACTIONS(66), 7,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_hostname,
      anon_sym_alias,
      anon_sym_line,
      anon_sym_archive,
      anon_sym_async_DASHbootp,
  [489] = 1,
    ACTIONS(68), 7,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_hostname,
      anon_sym_alias,
      anon_sym_line,
      anon_sym_archive,
      anon_sym_async_DASHbootp,
  [499] = 1,
    ACTIONS(70), 7,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_hostname,
      anon_sym_alias,
      anon_sym_line,
      anon_sym_archive,
      anon_sym_async_DASHbootp,
  [509] = 5,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(72), 1,
      anon_sym_BANG,
    STATE(101), 1,
      sym__alias_section,
    STATE(42), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [526] = 5,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(74), 1,
      anon_sym_BANG,
    STATE(67), 1,
      sym__alias_section,
    STATE(42), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [543] = 5,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(76), 1,
      anon_sym_BANG,
    STATE(85), 1,
      sym__alias_section,
    STATE(42), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [560] = 5,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(78), 1,
      anon_sym_BANG,
    STATE(95), 1,
      sym__alias_section,
    STATE(42), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [577] = 5,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(80), 1,
      anon_sym_BANG,
    STATE(78), 1,
      sym__alias_section,
    STATE(42), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [594] = 5,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(82), 1,
      anon_sym_BANG,
    STATE(94), 1,
      sym__alias_section,
    STATE(42), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [611] = 5,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(84), 1,
      anon_sym_BANG,
    STATE(79), 1,
      sym__alias_section,
    STATE(42), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [628] = 5,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(86), 1,
      anon_sym_BANG,
    STATE(104), 1,
      sym__alias_section,
    STATE(42), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [645] = 5,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(88), 1,
      anon_sym_BANG,
    STATE(105), 1,
      sym__alias_section,
    STATE(42), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [662] = 5,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(90), 1,
      anon_sym_BANG,
    STATE(108), 1,
      sym__alias_section,
    STATE(42), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [679] = 5,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    ACTIONS(92), 1,
      anon_sym_BANG,
    STATE(111), 1,
      sym__alias_section,
    STATE(42), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [696] = 1,
    ACTIONS(94), 6,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_hostname,
      anon_sym_alias,
      anon_sym_line,
      anon_sym_async_DASHbootp,
  [705] = 5,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    ACTIONS(96), 1,
      anon_sym_BANG,
    STATE(115), 1,
      sym__alias_section,
    STATE(42), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [722] = 5,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    ACTIONS(98), 1,
      anon_sym_BANG,
    STATE(110), 1,
      sym__alias_section,
    STATE(42), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [739] = 5,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    ACTIONS(100), 1,
      anon_sym_BANG,
    STATE(114), 1,
      sym__alias_section,
    STATE(42), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [756] = 5,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(102), 1,
      anon_sym_BANG,
    STATE(87), 1,
      sym__alias_section,
    STATE(42), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [773] = 5,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
    ACTIONS(106), 1,
      anon_sym_BANG,
    STATE(116), 1,
      sym__alias_section,
    STATE(42), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [790] = 1,
    ACTIONS(108), 5,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_hostname,
      anon_sym_alias,
      anon_sym_line,
  [798] = 1,
    ACTIONS(110), 5,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_hostname,
      anon_sym_alias,
      anon_sym_line,
  [806] = 3,
    ACTIONS(112), 1,
      anon_sym_BANG,
    ACTIONS(114), 1,
      anon_sym_alias,
    STATE(41), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [817] = 3,
    ACTIONS(15), 1,
      anon_sym_alias,
    ACTIONS(117), 1,
      anon_sym_BANG,
    STATE(41), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [828] = 1,
    ACTIONS(119), 4,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_hostname,
      anon_sym_alias,
  [835] = 1,
    ACTIONS(121), 3,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_alias,
  [841] = 2,
    STATE(54), 1,
      sym_line_type,
    ACTIONS(123), 2,
      anon_sym_console,
      anon_sym_tty0,
  [849] = 3,
    ACTIONS(11), 1,
      anon_sym_no,
    ACTIONS(125), 1,
      anon_sym_BANG,
    STATE(84), 1,
      sym_service_statements,
  [859] = 2,
    STATE(82), 1,
      sym_mode,
    ACTIONS(127), 2,
      anon_sym_exec,
      anon_sym_foo,
  [867] = 2,
    ACTIONS(129), 1,
      anon_sym_path,
    STATE(91), 1,
      sym__archive_path,
  [874] = 2,
    ACTIONS(131), 1,
      anon_sym_bootfile,
    STATE(57), 1,
      sym_async_bootp_tag,
  [881] = 2,
    ACTIONS(133), 1,
      aux_sym_running_version_token1,
    STATE(72), 1,
      sym_running_version,
  [888] = 2,
    ACTIONS(135), 1,
      anon_sym_BANG,
    STATE(93), 1,
      sym__running_version,
  [895] = 1,
    ACTIONS(137), 2,
      anon_sym_BANG,
      anon_sym_no,
  [900] = 1,
    ACTIONS(139), 2,
      anon_sym_BANG,
      anon_sym_no,
  [905] = 2,
    ACTIONS(141), 1,
      anon_sym_activation_DASHcharacter,
    STATE(62), 1,
      sym_activation_character,
  [912] = 1,
    ACTIONS(143), 2,
      anon_sym_BANG,
      anon_sym_alias,
  [917] = 1,
    ACTIONS(145), 2,
      sym_async_bootp_hostname,
      sym_async_bootp_data,
  [922] = 2,
    ACTIONS(147), 1,
      sym_async_bootp_hostname,
    ACTIONS(149), 1,
      sym_async_bootp_data,
  [929] = 2,
    ACTIONS(151), 1,
      aux_sym_running_version_token1,
    STATE(53), 1,
      sym_configured_version,
  [936] = 1,
    ACTIONS(153), 1,
      anon_sym_activation_DASHcharacter,
  [940] = 1,
    ACTIONS(155), 1,
      sym_command,
  [944] = 1,
    ACTIONS(157), 1,
      sym_ascii_value,
  [948] = 1,
    ACTIONS(159), 1,
      anon_sym_BANG,
  [952] = 1,
    ACTIONS(161), 1,
      anon_sym_end,
  [956] = 1,
    ACTIONS(163), 1,
      anon_sym_BANG,
  [960] = 1,
    ACTIONS(165), 1,
      sym_async_bootp_data,
  [964] = 1,
    ACTIONS(167), 1,
      anon_sym_BANG,
  [968] = 1,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
  [972] = 1,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
  [976] = 1,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
  [980] = 1,
    ACTIONS(169), 1,
      anon_sym_BANG,
  [984] = 1,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
  [988] = 1,
    ACTIONS(171), 1,
      anon_sym_BANG,
  [992] = 1,
    ACTIONS(173), 1,
      anon_sym_version,
  [996] = 1,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
  [1000] = 1,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
  [1004] = 1,
    ACTIONS(175), 1,
      anon_sym_pad,
  [1008] = 1,
    ACTIONS(177), 1,
      anon_sym_BANG,
  [1012] = 1,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
  [1016] = 1,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
  [1020] = 1,
    ACTIONS(179), 1,
      sym_alias,
  [1024] = 1,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
  [1028] = 1,
    ACTIONS(181), 1,
      sym_alias,
  [1032] = 1,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
  [1036] = 1,
    ACTIONS(183), 1,
      anon_sym_BANG,
  [1040] = 1,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
  [1044] = 1,
    ACTIONS(185), 1,
      anon_sym_BANG,
  [1048] = 1,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
  [1052] = 1,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
  [1056] = 1,
    ACTIONS(187), 1,
      anon_sym_BANG,
  [1060] = 1,
    ACTIONS(189), 1,
      sym_file_path,
  [1064] = 1,
    ACTIONS(191), 1,
      anon_sym_end,
  [1068] = 1,
    ACTIONS(193), 1,
      anon_sym_BANG,
  [1072] = 1,
    ACTIONS(195), 1,
      anon_sym_BANG,
  [1076] = 1,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
  [1080] = 1,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
  [1084] = 1,
    ACTIONS(197), 1,
      ts_builtin_sym_end,
  [1088] = 1,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
  [1092] = 1,
    ACTIONS(199), 1,
      ts_builtin_sym_end,
  [1096] = 1,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
  [1100] = 1,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
  [1104] = 1,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
  [1108] = 1,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
  [1112] = 1,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
  [1116] = 1,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
  [1120] = 1,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
  [1124] = 1,
    ACTIONS(201), 1,
      anon_sym_service,
  [1128] = 1,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
  [1132] = 1,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
  [1136] = 1,
    ACTIONS(203), 1,
      sym_value,
  [1140] = 1,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
  [1144] = 1,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
  [1148] = 1,
    ACTIONS(205), 1,
      anon_sym_BANG,
  [1152] = 1,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
  [1156] = 1,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
  [1160] = 1,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
  [1164] = 1,
    ACTIONS(207), 1,
      ts_builtin_sym_end,
  [1168] = 1,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 56,
  [SMALL_STATE(4)] = 97,
  [SMALL_STATE(5)] = 132,
  [SMALL_STATE(6)] = 167,
  [SMALL_STATE(7)] = 196,
  [SMALL_STATE(8)] = 225,
  [SMALL_STATE(9)] = 254,
  [SMALL_STATE(10)] = 283,
  [SMALL_STATE(11)] = 306,
  [SMALL_STATE(12)] = 329,
  [SMALL_STATE(13)] = 352,
  [SMALL_STATE(14)] = 375,
  [SMALL_STATE(15)] = 398,
  [SMALL_STATE(16)] = 421,
  [SMALL_STATE(17)] = 444,
  [SMALL_STATE(18)] = 467,
  [SMALL_STATE(19)] = 479,
  [SMALL_STATE(20)] = 489,
  [SMALL_STATE(21)] = 499,
  [SMALL_STATE(22)] = 509,
  [SMALL_STATE(23)] = 526,
  [SMALL_STATE(24)] = 543,
  [SMALL_STATE(25)] = 560,
  [SMALL_STATE(26)] = 577,
  [SMALL_STATE(27)] = 594,
  [SMALL_STATE(28)] = 611,
  [SMALL_STATE(29)] = 628,
  [SMALL_STATE(30)] = 645,
  [SMALL_STATE(31)] = 662,
  [SMALL_STATE(32)] = 679,
  [SMALL_STATE(33)] = 696,
  [SMALL_STATE(34)] = 705,
  [SMALL_STATE(35)] = 722,
  [SMALL_STATE(36)] = 739,
  [SMALL_STATE(37)] = 756,
  [SMALL_STATE(38)] = 773,
  [SMALL_STATE(39)] = 790,
  [SMALL_STATE(40)] = 798,
  [SMALL_STATE(41)] = 806,
  [SMALL_STATE(42)] = 817,
  [SMALL_STATE(43)] = 828,
  [SMALL_STATE(44)] = 835,
  [SMALL_STATE(45)] = 841,
  [SMALL_STATE(46)] = 849,
  [SMALL_STATE(47)] = 859,
  [SMALL_STATE(48)] = 867,
  [SMALL_STATE(49)] = 874,
  [SMALL_STATE(50)] = 881,
  [SMALL_STATE(51)] = 888,
  [SMALL_STATE(52)] = 895,
  [SMALL_STATE(53)] = 900,
  [SMALL_STATE(54)] = 905,
  [SMALL_STATE(55)] = 912,
  [SMALL_STATE(56)] = 917,
  [SMALL_STATE(57)] = 922,
  [SMALL_STATE(58)] = 929,
  [SMALL_STATE(59)] = 936,
  [SMALL_STATE(60)] = 940,
  [SMALL_STATE(61)] = 944,
  [SMALL_STATE(62)] = 948,
  [SMALL_STATE(63)] = 952,
  [SMALL_STATE(64)] = 956,
  [SMALL_STATE(65)] = 960,
  [SMALL_STATE(66)] = 964,
  [SMALL_STATE(67)] = 968,
  [SMALL_STATE(68)] = 972,
  [SMALL_STATE(69)] = 976,
  [SMALL_STATE(70)] = 980,
  [SMALL_STATE(71)] = 984,
  [SMALL_STATE(72)] = 988,
  [SMALL_STATE(73)] = 992,
  [SMALL_STATE(74)] = 996,
  [SMALL_STATE(75)] = 1000,
  [SMALL_STATE(76)] = 1004,
  [SMALL_STATE(77)] = 1008,
  [SMALL_STATE(78)] = 1012,
  [SMALL_STATE(79)] = 1016,
  [SMALL_STATE(80)] = 1020,
  [SMALL_STATE(81)] = 1024,
  [SMALL_STATE(82)] = 1028,
  [SMALL_STATE(83)] = 1032,
  [SMALL_STATE(84)] = 1036,
  [SMALL_STATE(85)] = 1040,
  [SMALL_STATE(86)] = 1044,
  [SMALL_STATE(87)] = 1048,
  [SMALL_STATE(88)] = 1052,
  [SMALL_STATE(89)] = 1056,
  [SMALL_STATE(90)] = 1060,
  [SMALL_STATE(91)] = 1064,
  [SMALL_STATE(92)] = 1068,
  [SMALL_STATE(93)] = 1072,
  [SMALL_STATE(94)] = 1076,
  [SMALL_STATE(95)] = 1080,
  [SMALL_STATE(96)] = 1084,
  [SMALL_STATE(97)] = 1088,
  [SMALL_STATE(98)] = 1092,
  [SMALL_STATE(99)] = 1096,
  [SMALL_STATE(100)] = 1100,
  [SMALL_STATE(101)] = 1104,
  [SMALL_STATE(102)] = 1108,
  [SMALL_STATE(103)] = 1112,
  [SMALL_STATE(104)] = 1116,
  [SMALL_STATE(105)] = 1120,
  [SMALL_STATE(106)] = 1124,
  [SMALL_STATE(107)] = 1128,
  [SMALL_STATE(108)] = 1132,
  [SMALL_STATE(109)] = 1136,
  [SMALL_STATE(110)] = 1140,
  [SMALL_STATE(111)] = 1144,
  [SMALL_STATE(112)] = 1148,
  [SMALL_STATE(113)] = 1152,
  [SMALL_STATE(114)] = 1156,
  [SMALL_STATE(115)] = 1160,
  [SMALL_STATE(116)] = 1164,
  [SMALL_STATE(117)] = 1168,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_configuration_file, 3, 0, 1),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_configuration_file, 4, 0, 1),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_configuration_file, 5, 0, 1),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_configuration_file, 6, 0, 1),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_configuration_file, 7, 0, 1),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_service_section, 1, 0, 0), REDUCE(sym__alias_section, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_service_section, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_service_section, 2, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_service_section, 3, 0, 4),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_service_section, 2, 0, 4),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_archive_section, 4, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_configuration_file, 8, 0, 1),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_async_bootp_section, 4, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_async_bootp_section, 5, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__alias_section_repeat1, 2, 0, 0),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__alias_section_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_section, 4, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hostname_section, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_configured_version, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__configured_version, 2, 0, 3),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias_statement, 4, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_async_bootp_tag, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_type, 1, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__archive_path, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_running_version, 1, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__running_version, 3, 0, 2),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mode, 1, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_activation_character, 2, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__alias_section, 2, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_service_statements, 3, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_configuration_file, 9, 0, 1),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_cisco_ios(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "cisco_ios",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 2,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
