version: 2

builds:
  - env:
      - CGO_ENABLED=1
      - CC={{ .Env.CC_WRAPPER }}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Tag}}

archives:
  - formats:
      - binary

release:
  github:
    owner: dgethings
    name: chunter
