.PHONY: all lsp clean release snapshot release-dry-run generate test test-lsp test-ts

TS ?= tree-sitter
TS_DIR := ../tree-sitter-cisco-ios-jinja2
TS_GRAMMAR := $(TS_DIR)/grammar.js
TS_PARSER := $(TS_DIR)/src/parser.c
# Go's cgo cache does not track the parser.c that binding.go #includes, so
# after `tree-sitter generate` Go keeps compiling the old grammar. Writing a
# Go file whose contents derive from parser.c's hash into the binding package
# makes the cache key change whenever the grammar changes.
TS_HASH_GO := $(TS_DIR)/bindings/go/parser_hash.go
TS_STAMP := .ts-gen-stamp
BIN := bin/chunter

SRCS := $(wildcard main.go cmd/*.go) $(shell find internal -name '*.go')

VERSION := $(shell svu current 2>/dev/null || echo "0.0.0")
NEXT    := $(shell svu next)
# RELEASE_TAG is the version we build and publish. For a normal release it
# equals NEXT. When NEXT == VERSION and the VERSION tag already exists, a
# previous `make release` pushed the tag but died before goreleaser ran; in
# that case we resume by releasing VERSION. When NEXT == VERSION and the
# tag does not exist, RELEASE_TAG stays empty and the release target errors
# out below.
ifeq ($(NEXT),$(VERSION))
  RESUMING    := $(if $(shell git tag -l "$(VERSION)"),1,)
  RELEASE_TAG := $(if $(RESUMING),$(VERSION),)
else
  RESUMING    :=
  RELEASE_TAG := $(NEXT)
endif
ROOT_DIR := $(shell pwd)
CC_WRAPPER := $(ROOT_DIR)/scripts/cc
# Fall back to the `gh` CLI's keyring token when GITHUB_TOKEN isn't in the
# environment. Recursive expansion (=) means `gh auth token` only runs when
# the variable is actually referenced (e.g. by `make release`).
GITHUB_TOKEN ?= $(shell gh auth token)

export CC_WRAPPER
export GITHUB_TOKEN

all: $(BIN)

$(TS_STAMP): $(TS_GRAMMAR)
	cd $(TS_DIR) && make
	@hash=$$(shasum -a 256 $(TS_PARSER) | cut -c1-16); \
	tmp=$(TS_HASH_GO).tmp; \
	printf 'package tree_sitter_cisco_ios_jinja2\n\n// Code generated by make. DO NOT EDIT.\nconst parserSHA256 = "%s"\n' "$$hash" > $$tmp; \
	cmp -s $$tmp $(TS_HASH_GO) && rm $$tmp || mv $$tmp $(TS_HASH_GO)
	@touch $@

generate: $(TS_STAMP)

$(BIN): $(TS_STAMP) $(SRCS)
	CGO_ENABLED=1 go build -o $(BIN) .

lsp:
	CGO_ENABLED=1 go build -o $(BIN) .

test: test-lsp test-ts

test-lsp: $(TS_STAMP)
	CGO_ENABLED=1 go test -race ./...

test-ts: $(TS_STAMP)
	cd $(TS_DIR) && $(TS) test

clean:
	go clean -cache
	rm -f $(BIN) $(TS_STAMP)
	$(MAKE) -C $(TS_DIR) clean

release:
ifeq ($(RELEASE_TAG),)
	$(error No new conventional commits since $(VERSION) (svu next=$(NEXT)). Add a feat:/fix: commit, or tag manually to force a release.)
endif
	@echo "Releasing $(RELEASE_TAG) (current: $(VERSION), next: $(NEXT), resuming: $(if $(RESUMING),yes,no))"
	@if [ -z "$(RESUMING)" ]; then \
		if git tag -l "$(RELEASE_TAG)" | grep -q "$(RELEASE_TAG)"; then \
			echo "Tag $(RELEASE_TAG) already exists; aborting to avoid re-publishing." >&2; \
			exit 1; \
		fi; \
		git tag -a "$(RELEASE_TAG)" -m "Release $(RELEASE_TAG)"; \
		git push origin "$(RELEASE_TAG)"; \
	else \
		echo "  (resume: tag $(RELEASE_TAG) already pushed, skipping tag step)"; \
	fi
	goreleaser release --clean
	gh release upload $(RELEASE_TAG) dist/config.yaml dist/metadata.json dist/artifacts.json

snapshot:
	goreleaser release --snapshot --clean

release-dry-run:
	@echo "Current: $(VERSION) -> Next: $(NEXT)"
	goreleaser release --snapshot --clean
