.PHONY: all lsp clean release snapshot release-dry-run generate test test-lsp test-ts

TS ?= tree-sitter
TS_DIR := ../tree-sitter-cisco-ios-jinja2
TS_GRAMMAR := $(TS_DIR)/grammar.js
TS_PARSER := $(TS_DIR)/src/parser.c
# Go's cgo cache does not track the parser.c that binding.go #includes, so
# after `tree-sitter generate` Go keeps compiling the old grammar. Writing a
# Go file whose contents derive from parser.c's hash into the binding package
# makes the cache key change whenever the grammar changes.
TS_HASH_GO := $(TS_DIR)/bindings/go/parser_hash.go
TS_STAMP := .ts-gen-stamp
BIN := bin/chunter

SRCS := $(wildcard main.go cmd/*.go) $(shell find internal -name '*.go')

VERSION := $(shell svu current 2>/dev/null || echo "0.0.0")
NEXT    := $(shell svu next)
ROOT_DIR := $(shell pwd)
CC_WRAPPER := $(ROOT_DIR)/scripts/cc

export CC_WRAPPER

all: $(BIN)

$(TS_STAMP): $(TS_GRAMMAR)
	cd $(TS_DIR) && make
	@hash=$$(shasum -a 256 $(TS_PARSER) | cut -c1-16); \
	tmp=$(TS_HASH_GO).tmp; \
	printf 'package tree_sitter_cisco_ios_jinja2\n\n// Code generated by make. DO NOT EDIT.\nconst parserSHA256 = "%s"\n' "$$hash" > $$tmp; \
	cmp -s $$tmp $(TS_HASH_GO) && rm $$tmp || mv $$tmp $(TS_HASH_GO)
	@touch $@

generate: $(TS_STAMP)

$(BIN): $(TS_STAMP) $(SRCS)
	CGO_ENABLED=1 go build -o $(BIN) .

lsp:
	CGO_ENABLED=1 go build -o $(BIN) .

test: test-lsp test-ts

test-lsp: $(TS_STAMP)
	CGO_ENABLED=1 go test ./...

test-ts: $(TS_STAMP)
	cd $(TS_DIR) && $(TS) test

clean:
	go clean -cache
	rm -f $(BIN) $(TS_STAMP)
	$(MAKE) -C $(TS_DIR) clean

release:
	@if git tag -l "$(NEXT)" | grep -q "$(NEXT)"; then \
		echo "Tag $(NEXT) already exists, running goreleaser only"; \
	elif [ "$(NEXT)" = "$(VERSION)" ]; then \
		echo "No new conventional commits since $(VERSION). Commit feat:/fix: changes first."; \
		exit 1; \
	else \
		echo "Releasing $(NEXT) (current: $(VERSION))"; \
		git tag -a "$(NEXT)" -m "Release $(NEXT)"; \
		git push origin "$(NEXT)"; \
	fi
	goreleaser release --clean
	gh release upload $(NEXT) dist/config.yaml dist/metadata.json dist/artifacts.json

snapshot:
	goreleaser release --snapshot --clean

release-dry-run:
	@echo "Current: $(VERSION) -> Next: $(NEXT)"
	goreleaser release --snapshot --clean
