package cisco_ios_jinja2

// routerKeywordOverlay is a curated overlay for the generated keyword database
// (keywords.go): canonical router-process sub-commands the scraper registers
// only under an obscure section, causing wrong-section false positives inside
// `router` sections. Each entry is folded into the keyword.Set's
// section-validity index in New (see keyword.Set.AddValidSections); it does
// not change hover, completion, or diagnostic messages.
//
// Background: keywords.go is generated by an external scraper from Cisco's
// per-command reference pages. A command documented only under a rare sub-mode
// (e.g. `network` is documented for IPv6 PMIPv6) but canonically used inside
// router processes (OSPF/BGP) resolves to that obscure section and is flagged
// as wrong-section in config-router. This overlay is the chunter-side fix; the
// generator itself lives in a sibling repo. See chunter-vzy.
//
// Entries are conservative: only single-token commands that are unambiguously
// canonical router sub-commands. Commands absent from the DB entirely (e.g.
// `area`, `neighbor`, `redistribute`) need no entry — they are unknown and
// silently skipped, never false-flagged. Commands already correct in the DB
// (e.g. `passive-interface`, `default-information`, `maximum-paths`) are
// excluded. Validity inherits to sub-modes, so a config-router entry also
// covers config-router-af (BGP address-family) via IsValidInSection's ancestry
// check.
var routerKeywordOverlay = map[string][]string{
	// `network <ip> <wildcard> area <n>` (OSPF) and `network <ip> mask <m>`
	// (BGP) — the canonical way to advertise a network into a routing process.
	// The DB registers `network` only under config-ipv6-pmipv6-domain-mn /
	// config-ipv6-pmipv6-lma, so every router `network` line is a false
	// positive without this entry.
	"network": {"config-router"},
	// `router-id <id>` (OSPF/BGP/IS-IS). The DB registers `router-id` only
	// under config-l2vpn, so it is a false positive inside router sections.
	"router-id": {"config-router"},
}
