#!/bin/bash
case "${GOOS}-${GOARCH}" in
  linux-amd64)  exec zig cc -target x86_64-linux-musl "$@" ;;
  linux-arm64)  exec zig cc -target aarch64-linux-musl "$@" ;;
  darwin-*)      exec clang "$@" ;;
  *)             exec cc "$@" ;;
esac
