/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 138
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_BANG = 1,
  anon_sym_version = 2,
  aux_sym_running_version_token1 = 3,
  anon_sym_no = 4,
  anon_sym_service = 5,
  anon_sym_pad = 6,
  anon_sym_hostname = 7,
  sym_value = 8,
  anon_sym_alias = 9,
  anon_sym_exec = 10,
  anon_sym_foo = 11,
  sym_alias = 12,
  sym_command = 13,
  anon_sym_line = 14,
  anon_sym_console = 15,
  anon_sym_tty0 = 16,
  anon_sym_activation_DASHcharacter = 17,
  sym_ascii_value = 18,
  anon_sym_archive = 19,
  anon_sym_end = 20,
  anon_sym_path = 21,
  sym_file_path = 22,
  anon_sym_async_DASHbootp = 23,
  anon_sym_bootfile = 24,
  sym_async_bootp_hostname = 25,
  sym_async_bootp_data = 26,
  sym_global = 27,
  sym__running_version = 28,
  sym_running_version = 29,
  sym_service_section = 30,
  sym__configured_version = 31,
  sym_configured_version = 32,
  sym_service_statements = 33,
  sym_hostname = 34,
  sym__alias_section = 35,
  sym_alias_statement = 36,
  sym_mode = 37,
  sym_line_section = 38,
  sym_line_type = 39,
  sym_activation_character = 40,
  sym_archive_section = 41,
  sym__archive_path = 42,
  sym_async_bootp_section = 43,
  sym_async_bootp_tag = 44,
  aux_sym__alias_section_repeat1 = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_BANG] = "!",
  [anon_sym_version] = "version",
  [aux_sym_running_version_token1] = "running_version_token1",
  [anon_sym_no] = "no",
  [anon_sym_service] = "service",
  [anon_sym_pad] = "pad",
  [anon_sym_hostname] = "hostname",
  [sym_value] = "value",
  [anon_sym_alias] = "alias",
  [anon_sym_exec] = "exec",
  [anon_sym_foo] = "foo",
  [sym_alias] = "alias",
  [sym_command] = "command",
  [anon_sym_line] = "line",
  [anon_sym_console] = "console",
  [anon_sym_tty0] = "tty0",
  [anon_sym_activation_DASHcharacter] = "activation-character",
  [sym_ascii_value] = "ascii_value",
  [anon_sym_archive] = "archive",
  [anon_sym_end] = "end",
  [anon_sym_path] = "path",
  [sym_file_path] = "file_path",
  [anon_sym_async_DASHbootp] = "async-bootp",
  [anon_sym_bootfile] = "bootfile",
  [sym_async_bootp_hostname] = "async_bootp_hostname",
  [sym_async_bootp_data] = "async_bootp_data",
  [sym_global] = "global",
  [sym__running_version] = "_running_version",
  [sym_running_version] = "running_version",
  [sym_service_section] = "service_section",
  [sym__configured_version] = "_configured_version",
  [sym_configured_version] = "configured_version",
  [sym_service_statements] = "service_statements",
  [sym_hostname] = "hostname",
  [sym__alias_section] = "_alias_section",
  [sym_alias_statement] = "alias_statement",
  [sym_mode] = "mode",
  [sym_line_section] = "line_section",
  [sym_line_type] = "line_type",
  [sym_activation_character] = "activation_character",
  [sym_archive_section] = "archive_section",
  [sym__archive_path] = "_archive_path",
  [sym_async_bootp_section] = "async_bootp_section",
  [sym_async_bootp_tag] = "async_bootp_tag",
  [aux_sym__alias_section_repeat1] = "_alias_section_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_version] = anon_sym_version,
  [aux_sym_running_version_token1] = aux_sym_running_version_token1,
  [anon_sym_no] = anon_sym_no,
  [anon_sym_service] = anon_sym_service,
  [anon_sym_pad] = anon_sym_pad,
  [anon_sym_hostname] = anon_sym_hostname,
  [sym_value] = sym_value,
  [anon_sym_alias] = anon_sym_alias,
  [anon_sym_exec] = anon_sym_exec,
  [anon_sym_foo] = anon_sym_foo,
  [sym_alias] = sym_alias,
  [sym_command] = sym_command,
  [anon_sym_line] = anon_sym_line,
  [anon_sym_console] = anon_sym_console,
  [anon_sym_tty0] = anon_sym_tty0,
  [anon_sym_activation_DASHcharacter] = anon_sym_activation_DASHcharacter,
  [sym_ascii_value] = sym_ascii_value,
  [anon_sym_archive] = anon_sym_archive,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_path] = anon_sym_path,
  [sym_file_path] = sym_file_path,
  [anon_sym_async_DASHbootp] = anon_sym_async_DASHbootp,
  [anon_sym_bootfile] = anon_sym_bootfile,
  [sym_async_bootp_hostname] = sym_async_bootp_hostname,
  [sym_async_bootp_data] = sym_async_bootp_data,
  [sym_global] = sym_global,
  [sym__running_version] = sym__running_version,
  [sym_running_version] = sym_running_version,
  [sym_service_section] = sym_service_section,
  [sym__configured_version] = sym__configured_version,
  [sym_configured_version] = sym_configured_version,
  [sym_service_statements] = sym_service_statements,
  [sym_hostname] = sym_hostname,
  [sym__alias_section] = sym__alias_section,
  [sym_alias_statement] = sym_alias_statement,
  [sym_mode] = sym_mode,
  [sym_line_section] = sym_line_section,
  [sym_line_type] = sym_line_type,
  [sym_activation_character] = sym_activation_character,
  [sym_archive_section] = sym_archive_section,
  [sym__archive_path] = sym__archive_path,
  [sym_async_bootp_section] = sym_async_bootp_section,
  [sym_async_bootp_tag] = sym_async_bootp_tag,
  [aux_sym__alias_section_repeat1] = aux_sym__alias_section_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_version] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_running_version_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_no] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_service] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pad] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_hostname] = {
    .visible = true,
    .named = false,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_alias] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_exec] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_foo] = {
    .visible = true,
    .named = false,
  },
  [sym_alias] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_line] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_console] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tty0] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_activation_DASHcharacter] = {
    .visible = true,
    .named = false,
  },
  [sym_ascii_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_archive] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_path] = {
    .visible = true,
    .named = false,
  },
  [sym_file_path] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_async_DASHbootp] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bootfile] = {
    .visible = true,
    .named = false,
  },
  [sym_async_bootp_hostname] = {
    .visible = true,
    .named = true,
  },
  [sym_async_bootp_data] = {
    .visible = true,
    .named = true,
  },
  [sym_global] = {
    .visible = true,
    .named = true,
  },
  [sym__running_version] = {
    .visible = false,
    .named = true,
  },
  [sym_running_version] = {
    .visible = true,
    .named = true,
  },
  [sym_service_section] = {
    .visible = true,
    .named = true,
  },
  [sym__configured_version] = {
    .visible = false,
    .named = true,
  },
  [sym_configured_version] = {
    .visible = true,
    .named = true,
  },
  [sym_service_statements] = {
    .visible = true,
    .named = true,
  },
  [sym_hostname] = {
    .visible = true,
    .named = true,
  },
  [sym__alias_section] = {
    .visible = false,
    .named = true,
  },
  [sym_alias_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_mode] = {
    .visible = true,
    .named = true,
  },
  [sym_line_section] = {
    .visible = true,
    .named = true,
  },
  [sym_line_type] = {
    .visible = true,
    .named = true,
  },
  [sym_activation_character] = {
    .visible = true,
    .named = true,
  },
  [sym_archive_section] = {
    .visible = true,
    .named = true,
  },
  [sym__archive_path] = {
    .visible = false,
    .named = true,
  },
  [sym_async_bootp_section] = {
    .visible = true,
    .named = true,
  },
  [sym_async_bootp_tag] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__alias_section_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_configured_version = 1,
  field_hostname = 2,
  field_running_version = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_configured_version] = "configured_version",
  [field_hostname] = "hostname",
  [field_running_version] = "running_version",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_running_version, 0, .inherited = true},
  [1] =
    {field_configured_version, 1},
  [2] =
    {field_configured_version, 0, .inherited = true},
  [3] =
    {field_hostname, 1},
  [4] =
    {field_running_version, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(93);
      ADVANCE_MAP(
        '!', 94,
        '"', 91,
        ':', 92,
        'a', 16,
        'b', 60,
        'c', 54,
        'e', 47,
        'f', 63,
        'h', 55,
        'l', 37,
        'n', 56,
        'p', 6,
        's', 22,
        't', 77,
        'v', 30,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(112);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(106);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(120);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(17);
      END_STATE();
    case 5:
      if (lookahead == '0') ADVANCE(110);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(46);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(70);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(71);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(19);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(80);
      END_STATE();
    case 12:
      if (lookahead == 'b') ADVANCE(65);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(34);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(103);
      END_STATE();
    case 15:
      if (lookahead == 'c') ADVANCE(3);
      END_STATE();
    case 16:
      if (lookahead == 'c') ADVANCE(78);
      if (lookahead == 'l') ADVANCE(36);
      if (lookahead == 'r') ADVANCE(13);
      if (lookahead == 's') ADVANCE(86);
      END_STATE();
    case 17:
      if (lookahead == 'c') ADVANCE(35);
      END_STATE();
    case 18:
      if (lookahead == 'c') ADVANCE(26);
      END_STATE();
    case 19:
      if (lookahead == 'c') ADVANCE(81);
      END_STATE();
    case 20:
      if (lookahead == 'd') ADVANCE(114);
      END_STATE();
    case 21:
      if (lookahead == 'd') ADVANCE(99);
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(67);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(108);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(113);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(109);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(98);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(118);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(100);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(69);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(68);
      END_STATE();
    case 32:
      if (lookahead == 'f') ADVANCE(43);
      END_STATE();
    case 33:
      if (lookahead == 'h') ADVANCE(115);
      END_STATE();
    case 34:
      if (lookahead == 'h') ADVANCE(39);
      END_STATE();
    case 35:
      if (lookahead == 'h') ADVANCE(8);
      END_STATE();
    case 36:
      if (lookahead == 'i') ADVANCE(9);
      END_STATE();
    case 37:
      if (lookahead == 'i') ADVANCE(51);
      END_STATE();
    case 38:
      if (lookahead == 'i') ADVANCE(82);
      END_STATE();
    case 39:
      if (lookahead == 'i') ADVANCE(83);
      END_STATE();
    case 40:
      if (lookahead == 'i') ADVANCE(18);
      END_STATE();
    case 41:
      if (lookahead == 'i') ADVANCE(62);
      END_STATE();
    case 42:
      if (lookahead == 'i') ADVANCE(64);
      END_STATE();
    case 43:
      if (lookahead == 'i') ADVANCE(45);
      END_STATE();
    case 44:
      if (lookahead == 'l') ADVANCE(25);
      END_STATE();
    case 45:
      if (lookahead == 'l') ADVANCE(27);
      END_STATE();
    case 46:
      if (lookahead == 'm') ADVANCE(28);
      END_STATE();
    case 47:
      if (lookahead == 'n') ADVANCE(20);
      if (lookahead == 'x') ADVANCE(29);
      END_STATE();
    case 48:
      if (lookahead == 'n') ADVANCE(95);
      END_STATE();
    case 49:
      if (lookahead == 'n') ADVANCE(74);
      END_STATE();
    case 50:
      if (lookahead == 'n') ADVANCE(4);
      END_STATE();
    case 51:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 52:
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 53:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 54:
      if (lookahead == 'o') ADVANCE(49);
      END_STATE();
    case 55:
      if (lookahead == 'o') ADVANCE(72);
      END_STATE();
    case 56:
      if (lookahead == 'o') ADVANCE(97);
      END_STATE();
    case 57:
      if (lookahead == 'o') ADVANCE(104);
      END_STATE();
    case 58:
      if (lookahead == 'o') ADVANCE(44);
      END_STATE();
    case 59:
      if (lookahead == 'o') ADVANCE(75);
      END_STATE();
    case 60:
      if (lookahead == 'o') ADVANCE(59);
      END_STATE();
    case 61:
      if (lookahead == 'o') ADVANCE(76);
      END_STATE();
    case 62:
      if (lookahead == 'o') ADVANCE(48);
      END_STATE();
    case 63:
      if (lookahead == 'o') ADVANCE(57);
      END_STATE();
    case 64:
      if (lookahead == 'o') ADVANCE(50);
      END_STATE();
    case 65:
      if (lookahead == 'o') ADVANCE(61);
      END_STATE();
    case 66:
      if (lookahead == 'p') ADVANCE(117);
      END_STATE();
    case 67:
      if (lookahead == 'r') ADVANCE(84);
      END_STATE();
    case 68:
      if (lookahead == 'r') ADVANCE(111);
      END_STATE();
    case 69:
      if (lookahead == 'r') ADVANCE(73);
      END_STATE();
    case 70:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 71:
      if (lookahead == 's') ADVANCE(102);
      END_STATE();
    case 72:
      if (lookahead == 's') ADVANCE(79);
      END_STATE();
    case 73:
      if (lookahead == 's') ADVANCE(41);
      END_STATE();
    case 74:
      if (lookahead == 's') ADVANCE(58);
      END_STATE();
    case 75:
      if (lookahead == 't') ADVANCE(32);
      END_STATE();
    case 76:
      if (lookahead == 't') ADVANCE(66);
      END_STATE();
    case 77:
      if (lookahead == 't') ADVANCE(85);
      END_STATE();
    case 78:
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 79:
      if (lookahead == 't') ADVANCE(53);
      END_STATE();
    case 80:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 81:
      if (lookahead == 't') ADVANCE(31);
      END_STATE();
    case 82:
      if (lookahead == 'v') ADVANCE(11);
      END_STATE();
    case 83:
      if (lookahead == 'v') ADVANCE(24);
      END_STATE();
    case 84:
      if (lookahead == 'v') ADVANCE(40);
      END_STATE();
    case 85:
      if (lookahead == 'y') ADVANCE(5);
      END_STATE();
    case 86:
      if (lookahead == 'y') ADVANCE(52);
      END_STATE();
    case 87:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(87);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 88:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      END_STATE();
    case 89:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(89);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 90:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(90);
      if (('/' <= lookahead && lookahead <= ':') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 91:
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(2);
      END_STATE();
    case 92:
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_version);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_running_version_token1);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_no);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_service);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_pad);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_hostname);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_value);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_alias);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_exec);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_foo);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_alias);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_command);
      if (lookahead == ' ') ADVANCE(106);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_command);
      if (lookahead == ' ' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_line);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_console);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_tty0);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_activation_DASHcharacter);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_ascii_value);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(112);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_archive);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_path);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_file_path);
      if (('/' <= lookahead && lookahead <= ':') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_async_DASHbootp);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_bootfile);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_async_bootp_hostname);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_async_bootp_data);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 87},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 87},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 88},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 89},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 89},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 1},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 90},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_version] = ACTIONS(1),
    [anon_sym_no] = ACTIONS(1),
    [anon_sym_service] = ACTIONS(1),
    [anon_sym_pad] = ACTIONS(1),
    [anon_sym_hostname] = ACTIONS(1),
    [anon_sym_alias] = ACTIONS(1),
    [anon_sym_exec] = ACTIONS(1),
    [anon_sym_foo] = ACTIONS(1),
    [anon_sym_line] = ACTIONS(1),
    [anon_sym_console] = ACTIONS(1),
    [anon_sym_tty0] = ACTIONS(1),
    [anon_sym_activation_DASHcharacter] = ACTIONS(1),
    [sym_ascii_value] = ACTIONS(1),
    [anon_sym_archive] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_path] = ACTIONS(1),
    [anon_sym_async_DASHbootp] = ACTIONS(1),
    [anon_sym_bootfile] = ACTIONS(1),
    [sym_async_bootp_hostname] = ACTIONS(1),
    [sym_async_bootp_data] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_global] = STATE(77),
    [sym__running_version] = STATE(2),
    [sym_service_section] = STATE(3),
    [sym__configured_version] = STATE(62),
    [sym_service_statements] = STATE(82),
    [sym_hostname] = STATE(42),
    [sym__alias_section] = STATE(85),
    [sym_alias_statement] = STATE(60),
    [sym_line_section] = STATE(28),
    [sym_archive_section] = STATE(6),
    [sym_async_bootp_section] = STATE(11),
    [aux_sym__alias_section_repeat1] = STATE(60),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_BANG] = ACTIONS(5),
    [anon_sym_version] = ACTIONS(7),
    [anon_sym_no] = ACTIONS(9),
    [anon_sym_hostname] = ACTIONS(11),
    [anon_sym_alias] = ACTIONS(13),
    [anon_sym_line] = ACTIONS(15),
    [anon_sym_archive] = ACTIONS(17),
    [anon_sym_async_DASHbootp] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 18,
    ACTIONS(7), 1,
      anon_sym_version,
    ACTIONS(9), 1,
      anon_sym_no,
    ACTIONS(11), 1,
      anon_sym_hostname,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(15), 1,
      anon_sym_line,
    ACTIONS(17), 1,
      anon_sym_archive,
    ACTIONS(19), 1,
      anon_sym_async_DASHbootp,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      anon_sym_BANG,
    STATE(4), 1,
      sym_service_section,
    STATE(7), 1,
      sym_archive_section,
    STATE(9), 1,
      sym_async_bootp_section,
    STATE(24), 1,
      sym_line_section,
    STATE(39), 1,
      sym_hostname,
    STATE(62), 1,
      sym__configured_version,
    STATE(82), 1,
      sym_service_statements,
    STATE(128), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [56] = 13,
    ACTIONS(11), 1,
      anon_sym_hostname,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(15), 1,
      anon_sym_line,
    ACTIONS(17), 1,
      anon_sym_archive,
    ACTIONS(19), 1,
      anon_sym_async_DASHbootp,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      anon_sym_BANG,
    STATE(8), 1,
      sym_archive_section,
    STATE(10), 1,
      sym_async_bootp_section,
    STATE(19), 1,
      sym_line_section,
    STATE(40), 1,
      sym_hostname,
    STATE(81), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [97] = 13,
    ACTIONS(11), 1,
      anon_sym_hostname,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(15), 1,
      anon_sym_line,
    ACTIONS(17), 1,
      anon_sym_archive,
    ACTIONS(19), 1,
      anon_sym_async_DASHbootp,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(31), 1,
      anon_sym_BANG,
    STATE(5), 1,
      sym_archive_section,
    STATE(12), 1,
      sym_async_bootp_section,
    STATE(20), 1,
      sym_line_section,
    STATE(44), 1,
      sym_hostname,
    STATE(124), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [138] = 11,
    ACTIONS(11), 1,
      anon_sym_hostname,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(15), 1,
      anon_sym_line,
    ACTIONS(19), 1,
      anon_sym_async_DASHbootp,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      anon_sym_BANG,
    STATE(15), 1,
      sym_async_bootp_section,
    STATE(25), 1,
      sym_line_section,
    STATE(34), 1,
      sym_hostname,
    STATE(92), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [173] = 11,
    ACTIONS(11), 1,
      anon_sym_hostname,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(15), 1,
      anon_sym_line,
    ACTIONS(19), 1,
      anon_sym_async_DASHbootp,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      anon_sym_BANG,
    STATE(10), 1,
      sym_async_bootp_section,
    STATE(19), 1,
      sym_line_section,
    STATE(40), 1,
      sym_hostname,
    STATE(81), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [208] = 11,
    ACTIONS(11), 1,
      anon_sym_hostname,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(15), 1,
      anon_sym_line,
    ACTIONS(19), 1,
      anon_sym_async_DASHbootp,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(37), 1,
      anon_sym_BANG,
    STATE(13), 1,
      sym_async_bootp_section,
    STATE(21), 1,
      sym_line_section,
    STATE(36), 1,
      sym_hostname,
    STATE(78), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [243] = 11,
    ACTIONS(11), 1,
      anon_sym_hostname,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(15), 1,
      anon_sym_line,
    ACTIONS(19), 1,
      anon_sym_async_DASHbootp,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(41), 1,
      anon_sym_BANG,
    STATE(14), 1,
      sym_async_bootp_section,
    STATE(29), 1,
      sym_line_section,
    STATE(37), 1,
      sym_hostname,
    STATE(76), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [278] = 9,
    ACTIONS(11), 1,
      anon_sym_hostname,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(15), 1,
      anon_sym_line,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(43), 1,
      anon_sym_BANG,
    STATE(22), 1,
      sym_line_section,
    STATE(52), 1,
      sym_hostname,
    STATE(87), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [307] = 9,
    ACTIONS(11), 1,
      anon_sym_hostname,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(15), 1,
      anon_sym_line,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(41), 1,
      anon_sym_BANG,
    STATE(29), 1,
      sym_line_section,
    STATE(37), 1,
      sym_hostname,
    STATE(76), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [336] = 9,
    ACTIONS(11), 1,
      anon_sym_hostname,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(15), 1,
      anon_sym_line,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      anon_sym_BANG,
    STATE(19), 1,
      sym_line_section,
    STATE(40), 1,
      sym_hostname,
    STATE(81), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [365] = 9,
    ACTIONS(11), 1,
      anon_sym_hostname,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(15), 1,
      anon_sym_line,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(45), 1,
      anon_sym_BANG,
    STATE(26), 1,
      sym_line_section,
    STATE(43), 1,
      sym_hostname,
    STATE(96), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [394] = 9,
    ACTIONS(11), 1,
      anon_sym_hostname,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(15), 1,
      anon_sym_line,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(47), 1,
      anon_sym_BANG,
    STATE(27), 1,
      sym_line_section,
    STATE(46), 1,
      sym_hostname,
    STATE(137), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [423] = 9,
    ACTIONS(11), 1,
      anon_sym_hostname,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(15), 1,
      anon_sym_line,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    ACTIONS(51), 1,
      anon_sym_BANG,
    STATE(17), 1,
      sym_line_section,
    STATE(49), 1,
      sym_hostname,
    STATE(108), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [452] = 9,
    ACTIONS(11), 1,
      anon_sym_hostname,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(15), 1,
      anon_sym_line,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    ACTIONS(55), 1,
      anon_sym_BANG,
    STATE(18), 1,
      sym_line_section,
    STATE(51), 1,
      sym_hostname,
    STATE(117), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [481] = 1,
    ACTIONS(57), 9,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_version,
      anon_sym_no,
      anon_sym_hostname,
      anon_sym_alias,
      anon_sym_line,
      anon_sym_archive,
      anon_sym_async_DASHbootp,
  [493] = 7,
    ACTIONS(11), 1,
      anon_sym_hostname,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    ACTIONS(61), 1,
      anon_sym_BANG,
    STATE(54), 1,
      sym_hostname,
    STATE(127), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [516] = 7,
    ACTIONS(11), 1,
      anon_sym_hostname,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
    ACTIONS(65), 1,
      anon_sym_BANG,
    STATE(55), 1,
      sym_hostname,
    STATE(132), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [539] = 7,
    ACTIONS(11), 1,
      anon_sym_hostname,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(41), 1,
      anon_sym_BANG,
    STATE(37), 1,
      sym_hostname,
    STATE(76), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [562] = 7,
    ACTIONS(11), 1,
      anon_sym_hostname,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(67), 1,
      anon_sym_BANG,
    STATE(41), 1,
      sym_hostname,
    STATE(90), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [585] = 7,
    ACTIONS(11), 1,
      anon_sym_hostname,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(69), 1,
      anon_sym_BANG,
    STATE(45), 1,
      sym_hostname,
    STATE(101), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [608] = 7,
    ACTIONS(11), 1,
      anon_sym_hostname,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(71), 1,
      anon_sym_BANG,
    STATE(48), 1,
      sym_hostname,
    STATE(107), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [631] = 3,
    ACTIONS(73), 1,
      ts_builtin_sym_end,
    ACTIONS(78), 1,
      anon_sym_version,
    ACTIONS(76), 6,
      anon_sym_BANG,
      anon_sym_hostname,
      anon_sym_alias,
      anon_sym_line,
      anon_sym_archive,
      anon_sym_async_DASHbootp,
  [646] = 7,
    ACTIONS(11), 1,
      anon_sym_hostname,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(80), 1,
      anon_sym_BANG,
    STATE(35), 1,
      sym_hostname,
    STATE(84), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [669] = 7,
    ACTIONS(11), 1,
      anon_sym_hostname,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    ACTIONS(82), 1,
      anon_sym_BANG,
    STATE(47), 1,
      sym_hostname,
    STATE(115), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [692] = 7,
    ACTIONS(11), 1,
      anon_sym_hostname,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    ACTIONS(84), 1,
      anon_sym_BANG,
    STATE(50), 1,
      sym_hostname,
    STATE(121), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [715] = 7,
    ACTIONS(11), 1,
      anon_sym_hostname,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    ACTIONS(86), 1,
      anon_sym_BANG,
    STATE(53), 1,
      sym_hostname,
    STATE(125), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [738] = 7,
    ACTIONS(11), 1,
      anon_sym_hostname,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      anon_sym_BANG,
    STATE(40), 1,
      sym_hostname,
    STATE(81), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [761] = 7,
    ACTIONS(11), 1,
      anon_sym_hostname,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    ACTIONS(51), 1,
      anon_sym_BANG,
    STATE(49), 1,
      sym_hostname,
    STATE(108), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [784] = 2,
    ACTIONS(73), 1,
      ts_builtin_sym_end,
    ACTIONS(76), 6,
      anon_sym_BANG,
      anon_sym_hostname,
      anon_sym_alias,
      anon_sym_line,
      anon_sym_archive,
      anon_sym_async_DASHbootp,
  [796] = 1,
    ACTIONS(88), 7,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_hostname,
      anon_sym_alias,
      anon_sym_line,
      anon_sym_archive,
      anon_sym_async_DASHbootp,
  [806] = 1,
    ACTIONS(90), 7,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_hostname,
      anon_sym_alias,
      anon_sym_line,
      anon_sym_archive,
      anon_sym_async_DASHbootp,
  [816] = 1,
    ACTIONS(92), 7,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_hostname,
      anon_sym_alias,
      anon_sym_line,
      anon_sym_archive,
      anon_sym_async_DASHbootp,
  [826] = 5,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    ACTIONS(94), 1,
      anon_sym_BANG,
    STATE(113), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [843] = 5,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(96), 1,
      anon_sym_BANG,
    STATE(98), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [860] = 5,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(98), 1,
      anon_sym_BANG,
    STATE(99), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [877] = 5,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    ACTIONS(51), 1,
      anon_sym_BANG,
    STATE(108), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [894] = 1,
    ACTIONS(100), 6,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_hostname,
      anon_sym_alias,
      anon_sym_line,
      anon_sym_async_DASHbootp,
  [903] = 5,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(102), 1,
      anon_sym_BANG,
    STATE(103), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [920] = 5,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(41), 1,
      anon_sym_BANG,
    STATE(76), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [937] = 5,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    ACTIONS(104), 1,
      anon_sym_BANG,
    STATE(112), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [954] = 5,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      anon_sym_BANG,
    STATE(81), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [971] = 5,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    ACTIONS(106), 1,
      anon_sym_BANG,
    STATE(119), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [988] = 5,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(108), 1,
      anon_sym_BANG,
    STATE(88), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [1005] = 5,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    ACTIONS(110), 1,
      anon_sym_BANG,
    STATE(122), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [1022] = 5,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    ACTIONS(112), 1,
      anon_sym_BANG,
    STATE(123), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [1039] = 5,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
    ACTIONS(114), 1,
      anon_sym_BANG,
    STATE(129), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [1056] = 5,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    ACTIONS(116), 1,
      anon_sym_BANG,
    STATE(126), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [1073] = 5,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    ACTIONS(61), 1,
      anon_sym_BANG,
    STATE(127), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [1090] = 5,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
    ACTIONS(118), 1,
      anon_sym_BANG,
    STATE(133), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [1107] = 5,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
    ACTIONS(120), 1,
      anon_sym_BANG,
    STATE(130), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [1124] = 5,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(122), 1,
      anon_sym_BANG,
    STATE(105), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [1141] = 5,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
    ACTIONS(124), 1,
      anon_sym_BANG,
    STATE(134), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [1158] = 5,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(126), 1,
      ts_builtin_sym_end,
    ACTIONS(128), 1,
      anon_sym_BANG,
    STATE(75), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [1175] = 5,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(130), 1,
      ts_builtin_sym_end,
    ACTIONS(132), 1,
      anon_sym_BANG,
    STATE(136), 1,
      sym__alias_section,
    STATE(60), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [1192] = 1,
    ACTIONS(134), 5,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_hostname,
      anon_sym_alias,
      anon_sym_line,
  [1200] = 1,
    ACTIONS(136), 5,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_hostname,
      anon_sym_alias,
      anon_sym_line,
  [1208] = 1,
    ACTIONS(138), 4,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_hostname,
      anon_sym_alias,
  [1215] = 3,
    ACTIONS(140), 1,
      anon_sym_BANG,
    ACTIONS(142), 1,
      anon_sym_alias,
    STATE(59), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [1226] = 3,
    ACTIONS(13), 1,
      anon_sym_alias,
    ACTIONS(145), 1,
      anon_sym_BANG,
    STATE(59), 2,
      sym_alias_statement,
      aux_sym__alias_section_repeat1,
  [1237] = 2,
    STATE(104), 1,
      sym_mode,
    ACTIONS(147), 2,
      anon_sym_exec,
      anon_sym_foo,
  [1245] = 3,
    ACTIONS(9), 1,
      anon_sym_no,
    ACTIONS(149), 1,
      anon_sym_BANG,
    STATE(91), 1,
      sym_service_statements,
  [1255] = 1,
    ACTIONS(151), 3,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_alias,
  [1261] = 2,
    STATE(66), 1,
      sym_line_type,
    ACTIONS(153), 2,
      anon_sym_console,
      anon_sym_tty0,
  [1269] = 2,
    ACTIONS(155), 1,
      anon_sym_path,
    STATE(135), 1,
      sym__archive_path,
  [1276] = 2,
    ACTIONS(157), 1,
      anon_sym_activation_DASHcharacter,
    STATE(110), 1,
      sym_activation_character,
  [1283] = 1,
    ACTIONS(159), 2,
      sym_async_bootp_hostname,
      sym_async_bootp_data,
  [1288] = 2,
    ACTIONS(161), 1,
      sym_async_bootp_hostname,
    ACTIONS(163), 1,
      sym_async_bootp_data,
  [1295] = 2,
    ACTIONS(165), 1,
      anon_sym_bootfile,
    STATE(68), 1,
      sym_async_bootp_tag,
  [1302] = 2,
    ACTIONS(167), 1,
      aux_sym_running_version_token1,
    STATE(74), 1,
      sym_configured_version,
  [1309] = 1,
    ACTIONS(169), 2,
      anon_sym_BANG,
      anon_sym_alias,
  [1314] = 2,
    ACTIONS(171), 1,
      aux_sym_running_version_token1,
    STATE(100), 1,
      sym_running_version,
  [1321] = 1,
    ACTIONS(173), 2,
      anon_sym_BANG,
      anon_sym_no,
  [1326] = 1,
    ACTIONS(175), 2,
      anon_sym_BANG,
      anon_sym_no,
  [1331] = 1,
    ACTIONS(177), 1,
      ts_builtin_sym_end,
  [1335] = 1,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
  [1339] = 1,
    ACTIONS(179), 1,
      ts_builtin_sym_end,
  [1343] = 1,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
  [1347] = 1,
    ACTIONS(181), 1,
      anon_sym_service,
  [1351] = 1,
    ACTIONS(183), 1,
      sym_value,
  [1355] = 1,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
  [1359] = 1,
    ACTIONS(185), 1,
      anon_sym_BANG,
  [1363] = 1,
    ACTIONS(187), 1,
      anon_sym_BANG,
  [1367] = 1,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
  [1371] = 1,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
  [1375] = 1,
    ACTIONS(189), 1,
      anon_sym_BANG,
  [1379] = 1,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
  [1383] = 1,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
  [1387] = 1,
    ACTIONS(191), 1,
      anon_sym_pad,
  [1391] = 1,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
  [1395] = 1,
    ACTIONS(193), 1,
      anon_sym_BANG,
  [1399] = 1,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
  [1403] = 1,
    ACTIONS(195), 1,
      anon_sym_BANG,
  [1407] = 1,
    ACTIONS(197), 1,
      ts_builtin_sym_end,
  [1411] = 1,
    ACTIONS(199), 1,
      sym_alias,
  [1415] = 1,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
  [1419] = 1,
    ACTIONS(201), 1,
      anon_sym_BANG,
  [1423] = 1,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
  [1427] = 1,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
  [1431] = 1,
    ACTIONS(203), 1,
      anon_sym_BANG,
  [1435] = 1,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
  [1439] = 1,
    ACTIONS(205), 1,
      anon_sym_BANG,
  [1443] = 1,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
  [1447] = 1,
    ACTIONS(207), 1,
      sym_alias,
  [1451] = 1,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
  [1455] = 1,
    ACTIONS(209), 1,
      sym_command,
  [1459] = 1,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
  [1463] = 1,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
  [1467] = 1,
    ACTIONS(211), 1,
      sym_ascii_value,
  [1471] = 1,
    ACTIONS(213), 1,
      anon_sym_BANG,
  [1475] = 1,
    ACTIONS(215), 1,
      anon_sym_end,
  [1479] = 1,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
  [1483] = 1,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
  [1487] = 1,
    ACTIONS(217), 1,
      anon_sym_BANG,
  [1491] = 1,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
  [1495] = 1,
    ACTIONS(219), 1,
      sym_async_bootp_data,
  [1499] = 1,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
  [1503] = 1,
    ACTIONS(221), 1,
      anon_sym_BANG,
  [1507] = 1,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
  [1511] = 1,
    ACTIONS(223), 1,
      anon_sym_activation_DASHcharacter,
  [1515] = 1,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
  [1519] = 1,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
  [1523] = 1,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
  [1527] = 1,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
  [1531] = 1,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
  [1535] = 1,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
  [1539] = 1,
    ACTIONS(126), 1,
      ts_builtin_sym_end,
  [1543] = 1,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
  [1547] = 1,
    ACTIONS(130), 1,
      ts_builtin_sym_end,
  [1551] = 1,
    ACTIONS(130), 1,
      ts_builtin_sym_end,
  [1555] = 1,
    ACTIONS(225), 1,
      sym_file_path,
  [1559] = 1,
    ACTIONS(130), 1,
      ts_builtin_sym_end,
  [1563] = 1,
    ACTIONS(130), 1,
      ts_builtin_sym_end,
  [1567] = 1,
    ACTIONS(130), 1,
      ts_builtin_sym_end,
  [1571] = 1,
    ACTIONS(227), 1,
      anon_sym_end,
  [1575] = 1,
    ACTIONS(229), 1,
      ts_builtin_sym_end,
  [1579] = 1,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 56,
  [SMALL_STATE(4)] = 97,
  [SMALL_STATE(5)] = 138,
  [SMALL_STATE(6)] = 173,
  [SMALL_STATE(7)] = 208,
  [SMALL_STATE(8)] = 243,
  [SMALL_STATE(9)] = 278,
  [SMALL_STATE(10)] = 307,
  [SMALL_STATE(11)] = 336,
  [SMALL_STATE(12)] = 365,
  [SMALL_STATE(13)] = 394,
  [SMALL_STATE(14)] = 423,
  [SMALL_STATE(15)] = 452,
  [SMALL_STATE(16)] = 481,
  [SMALL_STATE(17)] = 493,
  [SMALL_STATE(18)] = 516,
  [SMALL_STATE(19)] = 539,
  [SMALL_STATE(20)] = 562,
  [SMALL_STATE(21)] = 585,
  [SMALL_STATE(22)] = 608,
  [SMALL_STATE(23)] = 631,
  [SMALL_STATE(24)] = 646,
  [SMALL_STATE(25)] = 669,
  [SMALL_STATE(26)] = 692,
  [SMALL_STATE(27)] = 715,
  [SMALL_STATE(28)] = 738,
  [SMALL_STATE(29)] = 761,
  [SMALL_STATE(30)] = 784,
  [SMALL_STATE(31)] = 796,
  [SMALL_STATE(32)] = 806,
  [SMALL_STATE(33)] = 816,
  [SMALL_STATE(34)] = 826,
  [SMALL_STATE(35)] = 843,
  [SMALL_STATE(36)] = 860,
  [SMALL_STATE(37)] = 877,
  [SMALL_STATE(38)] = 894,
  [SMALL_STATE(39)] = 903,
  [SMALL_STATE(40)] = 920,
  [SMALL_STATE(41)] = 937,
  [SMALL_STATE(42)] = 954,
  [SMALL_STATE(43)] = 971,
  [SMALL_STATE(44)] = 988,
  [SMALL_STATE(45)] = 1005,
  [SMALL_STATE(46)] = 1022,
  [SMALL_STATE(47)] = 1039,
  [SMALL_STATE(48)] = 1056,
  [SMALL_STATE(49)] = 1073,
  [SMALL_STATE(50)] = 1090,
  [SMALL_STATE(51)] = 1107,
  [SMALL_STATE(52)] = 1124,
  [SMALL_STATE(53)] = 1141,
  [SMALL_STATE(54)] = 1158,
  [SMALL_STATE(55)] = 1175,
  [SMALL_STATE(56)] = 1192,
  [SMALL_STATE(57)] = 1200,
  [SMALL_STATE(58)] = 1208,
  [SMALL_STATE(59)] = 1215,
  [SMALL_STATE(60)] = 1226,
  [SMALL_STATE(61)] = 1237,
  [SMALL_STATE(62)] = 1245,
  [SMALL_STATE(63)] = 1255,
  [SMALL_STATE(64)] = 1261,
  [SMALL_STATE(65)] = 1269,
  [SMALL_STATE(66)] = 1276,
  [SMALL_STATE(67)] = 1283,
  [SMALL_STATE(68)] = 1288,
  [SMALL_STATE(69)] = 1295,
  [SMALL_STATE(70)] = 1302,
  [SMALL_STATE(71)] = 1309,
  [SMALL_STATE(72)] = 1314,
  [SMALL_STATE(73)] = 1321,
  [SMALL_STATE(74)] = 1326,
  [SMALL_STATE(75)] = 1331,
  [SMALL_STATE(76)] = 1335,
  [SMALL_STATE(77)] = 1339,
  [SMALL_STATE(78)] = 1343,
  [SMALL_STATE(79)] = 1347,
  [SMALL_STATE(80)] = 1351,
  [SMALL_STATE(81)] = 1355,
  [SMALL_STATE(82)] = 1359,
  [SMALL_STATE(83)] = 1363,
  [SMALL_STATE(84)] = 1367,
  [SMALL_STATE(85)] = 1371,
  [SMALL_STATE(86)] = 1375,
  [SMALL_STATE(87)] = 1379,
  [SMALL_STATE(88)] = 1383,
  [SMALL_STATE(89)] = 1387,
  [SMALL_STATE(90)] = 1391,
  [SMALL_STATE(91)] = 1395,
  [SMALL_STATE(92)] = 1399,
  [SMALL_STATE(93)] = 1403,
  [SMALL_STATE(94)] = 1407,
  [SMALL_STATE(95)] = 1411,
  [SMALL_STATE(96)] = 1415,
  [SMALL_STATE(97)] = 1419,
  [SMALL_STATE(98)] = 1423,
  [SMALL_STATE(99)] = 1427,
  [SMALL_STATE(100)] = 1431,
  [SMALL_STATE(101)] = 1435,
  [SMALL_STATE(102)] = 1439,
  [SMALL_STATE(103)] = 1443,
  [SMALL_STATE(104)] = 1447,
  [SMALL_STATE(105)] = 1451,
  [SMALL_STATE(106)] = 1455,
  [SMALL_STATE(107)] = 1459,
  [SMALL_STATE(108)] = 1463,
  [SMALL_STATE(109)] = 1467,
  [SMALL_STATE(110)] = 1471,
  [SMALL_STATE(111)] = 1475,
  [SMALL_STATE(112)] = 1479,
  [SMALL_STATE(113)] = 1483,
  [SMALL_STATE(114)] = 1487,
  [SMALL_STATE(115)] = 1491,
  [SMALL_STATE(116)] = 1495,
  [SMALL_STATE(117)] = 1499,
  [SMALL_STATE(118)] = 1503,
  [SMALL_STATE(119)] = 1507,
  [SMALL_STATE(120)] = 1511,
  [SMALL_STATE(121)] = 1515,
  [SMALL_STATE(122)] = 1519,
  [SMALL_STATE(123)] = 1523,
  [SMALL_STATE(124)] = 1527,
  [SMALL_STATE(125)] = 1531,
  [SMALL_STATE(126)] = 1535,
  [SMALL_STATE(127)] = 1539,
  [SMALL_STATE(128)] = 1543,
  [SMALL_STATE(129)] = 1547,
  [SMALL_STATE(130)] = 1551,
  [SMALL_STATE(131)] = 1555,
  [SMALL_STATE(132)] = 1559,
  [SMALL_STATE(133)] = 1563,
  [SMALL_STATE(134)] = 1567,
  [SMALL_STATE(135)] = 1571,
  [SMALL_STATE(136)] = 1575,
  [SMALL_STATE(137)] = 1579,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global, 1, 0, 1),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global, 2, 0, 1),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global, 3, 0, 1),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global, 3, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global, 4, 0, 1),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__running_version, 4, 0, 5),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global, 4, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global, 5, 0, 1),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_service_section, 1, 0, 0), REDUCE(sym__alias_section, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_service_section, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_service_section, 2, 0, 3),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_service_section, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_service_section, 3, 0, 3),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_archive_section, 4, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global, 5, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global, 6, 0, 1),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_async_bootp_section, 4, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_async_bootp_section, 5, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_section, 4, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__alias_section_repeat1, 2, 0, 0),
  [142] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__alias_section_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hostname, 3, 0, 4),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_async_bootp_tag, 1, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias_statement, 4, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_configured_version, 1, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__configured_version, 2, 0, 2),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global, 6, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_activation_character, 2, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__alias_section, 2, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mode, 1, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_running_version, 1, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_service_statements, 3, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__archive_path, 2, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_type, 1, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global, 7, 0, 1),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_cisco_ios(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "cisco_ios",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 2,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
